/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictationRouteImport } from './routes/dictation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SelftestRouteImport } from './routes/selftest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationRoute = DictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SelftestRoute = SelftestRouteImport.update({
  id: '/selftest',
  path: '/selftest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/privacy': typeof PrivacyRoute
  '/selftest': typeof SelftestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/privacy': typeof PrivacyRoute
  '/selftest': typeof SelftestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dictation': typeof DictationRoute
  '/privacy': typeof PrivacyRoute
  '/selftest': typeof SelftestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dictation' | '/privacy' | '/selftest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dictation' | '/privacy' | '/selftest'
  id: '__root__' | '/' | '/dictation' | '/privacy' | '/selftest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DictationRoute: typeof DictationRoute
  PrivacyRoute: typeof PrivacyRoute
  SelftestRoute: typeof SelftestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation': {
      id: '/dictation'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof DictationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selftest': {
      id: '/selftest'
      path: '/selftest'
      fullPath: '/selftest'
      preLoaderRoute: typeof SelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DictationRoute: DictationRoute,
  PrivacyRoute: PrivacyRoute,
  SelftestRoute: SelftestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
